//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSD_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public string ServiceCode { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime RequestStartDateTime { get; set; }
        public Nullable<System.DateTime> RequestCompleteDateTime { get; set; }
    }
}
